mozilla/mtu

.github/workflows/check.yml
src/lib.rs

On non-supported platforms, e.g. FreeBSD, the `mtu` crate is a no-op.
```rust
fn interface_and_mtu_impl(_socket: &UdpSocket) -> Result<(String, usize), Error> {
default_result()
}
```
Previously the function signature was off with its unix and windows equivalents.
This commit updates the function signature and adds a CI smoke-test for FreeBSD.

fix: return (String, usize) on non-supported platforms

---

.github/workflows/check.yml
README.md
src/lib.rs

This started out as a PR to add `vmactions`-based CI to the module, but it turns out that the BSDs need exactly the same code as macOS, so supporting them was easy.
Inspired by https://github.com/miguelcsx/mtu/commit/dfb6490fe98a72fdb11df09f18aace70288fc61a

feat: Support the BSDs

---

src/lib.rs

Receiving which indicates that we randomly picked a privileged port. This happens esp. on Windows, even with ports > 1024.
Broken out of #23

test: Pick another port on `PermissionDenied`

---

.github/workflows/check.yml
src/lib.rs

Similar to what was done for neqo.
Also address a spurious test failure when a privileged port was randomly chosen (since I ran a lot of tests during debugging I managed to hit that.)
TODO: Figure out why the `windows_bindgen` tests only succeeds when run via `llvm-cov`. That seems odd.

ci: Run more things in parallel and only when needed

---

Cargo.toml
src/lib.rs

Because otherwise, when used with neqo, the local port is already in use for the UDP socket used for the QUIC connection.
Also cut a new release for this.

fix: Let the OS choose an unused local port

---

.github/workflows/check.yml

It takes longer to install `nextest` than to run the tests with `cargo test`, esp. on Windows where there is no binary for `binstall` to grab.

ci: Drop `nextest`

---

Cargo.toml
build.rs

Because of course they do. Old way breaks macOS Firefox build. Not sure why, given that CI here worked. 🤷

fix: BSDs need different `#include`s

---

.github/workflows/check.yml

https://en.wikipedia.org/wiki/Code_coverage#Modified_condition/decision_coverage

ci: Enable MC/DC coverage

---

src/bsd.rs

Caught by clippy, see https://github.com/mozilla/mtu/actions/runs/12514012694/job/34909471469?pr=58.

fix(bsd): format string with format args

---

.github/workflows/check.yml

Equivalent to https://github.com/mozilla/neqo/pull/2301.

ci(sanitize): ignore leak in std::rt::lang_start_internal

---

.github/workflows/check.yml

See https://github.com/mozilla/neqo/pull/2353.
---
Related: I would advocate for moving mozilla/mtu into mozilla/neqo. That would reduce the CI maintenance burden.

 ci(sanitize): downgrade to ubuntu v22.04

---

build.rs
src/windows.rs

On Windows, IPv6 and IPv4 can have different MTU values.

family takes values based on IP type

---

.clippy.toml
Cargo.toml
build.rs
src/bsd.rs
src/linux.rs
src/routesocket.rs
src/windows.rs

chore: Add more lints

---

.github/workflows/check.yml

Reverts mozilla/mtu#69
See equivalent pull request https://github.com/mozilla/neqo/pull/2364 on the Neqo side.

Revert " ci(sanitize): downgrade to ubuntu v22.04"

---

Cargo.lock
Cargo.toml
build.rs
src/lib.rs
src/routesocket.rs

In a `build.rs` file `cfg(target_os = "linux")` refers to the target OS of the `build.rs` binary. The environment variable `CARGO_CFG_TARGET_OS` refers to the target OS of the final binary.
When cross-compiling, the target OS of the `build.rs` binary and the target OS of the final binary are not the same. The `mtu`'s `build.rs` should use `CARGO_CFG_TARGET_OS`.
In addition, `cfg(target_os = "linux")` does not include `android`. This commit `cfg`s `linux` and `android` everywhere.
---
Fixes https://github.com/mozilla/mtu/issues/78.

fix: use CARGO_CFG_TARGET_OS and target_os android

---

Cargo.lock
Cargo.toml
build.rs
src/bsd.rs
src/lib.rs

`net/route.h` seems to be unavailable on iOS, see #82 and various [related issue reports](https://www.google.com/search?client=ubuntu-sn&channel=fs&q=net%2Froute.h+ios).
As a hot-fix for Firefox, more specifically [bugzilla/1944802](https://bugzilla.mozilla.org/show_bug.cgi?id=1944802), I suggest dropping support for all Apple platforms, but `macos`.
Long term, we can tackle proper `ios`  support in `mtu`. Though, given that `ios` is only a tier 2 platform for Mozilla, and given that `mtu` only provides an optimization, this is not a priority.
---
Fixes https://github.com/mozilla/mtu/issues/82.

fix: drop all apple OSs but macos

---

.github/workflows/check.yml

Also set some reasonable test timeouts while I'm here.

ci: Fix `rustup` component installation

---

.github/workflows/actionlint.yml
.github/workflows/check.yml

We got rid of `latest` in #105. Fix the logic to account for that. (Also fix two instanced where we still used `latest`.)

ci: We no longer use `latest` runners

---

.github/workflows/check.yml

ci: `ubuntu-20` runners are retired

---

src/bsd.rs

OpenBSD supports multiple routing tables. The current code doesn't account for that and instead always request the route for routing table 0. If the process is run in another rtable, then this operation will get stuck. `getrtable` isn't part of `libc` crate, but part of OpenBSD's libc. The cast is safe: [the syscall never fails](https://github.com/openbsd/src/blob/master/sys/kern/uipc_syscalls.c#L1447), and the actual values are between 0 and 255.
Additional details can be found in:
- https://man.openbsd.org/rtable.4 for the mechanism in question
- https://man.openbsd.org/route.4#The_Routing_Socket for the fields in struct rt_msghdr, which includes the field that the patches set and isn't present in other BSDs
- https://man.openbsd.org/getrtable.2 for the syscall for obtaining the …

Support rtable on OpenBSD

---

.github/workflows/check.yml

Options around it seem to have changed, and it's of questionable benefit anyway.

ci: Turn off `--mcdc` coverage
